//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: hello.proto
namespace NPx
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HelloMessage")]
  public partial class HelloMessage : global::ProtoBuf.IExtensible
  {
    public HelloMessage() {}
    
    private int _number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private int _number2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"number2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number2
    {
      get { return _number2; }
      set { _number2 = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _stuff;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"stuff", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string stuff
    {
      get { return _stuff; }
      set { _stuff = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CloseAppMessage")]
  public partial class CloseAppMessage : global::ProtoBuf.IExtensible
  {
    public CloseAppMessage() {}
    
    private string _reason;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessagingSendDataMessage")]
  public partial class MessagingSendDataMessage : global::ProtoBuf.IExtensible
  {
    public MessagingSendDataMessage() {}
    
    private ulong _npid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"npid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong npid
    {
      get { return _npid; }
      set { _npid = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}