//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: servers.proto
namespace NPx
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SessionInfo")]
  public partial class SessionInfo : global::ProtoBuf.IExtensible
  {
    public SessionInfo() {}
    

    private uint _address = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint address
    {
      get { return _address; }
      set { _address = value; }
    }

    private int _port = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int port
    {
      get { return _port; }
      set { _port = value; }
    }

    private ulong _npid = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"npid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong npid
    {
      get { return _npid; }
      set { _npid = value; }
    }

    private string _hostname = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hostname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hostname
    {
      get { return _hostname; }
      set { _hostname = value; }
    }

    private string _mapname = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"mapname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mapname
    {
      get { return _mapname; }
      set { _mapname = value; }
    }

    private int _players = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int players
    {
      get { return _players; }
      set { _players = value; }
    }

    private int _maxplayers = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"maxplayers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxplayers
    {
      get { return _maxplayers; }
      set { _maxplayers = value; }
    }

    private int _version = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServersCreateSessionMessage")]
  public partial class ServersCreateSessionMessage : global::ProtoBuf.IExtensible
  {
    public ServersCreateSessionMessage() {}
    

    private SessionInfo _info = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SessionInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServersCreateSessionResultMessage")]
  public partial class ServersCreateSessionResultMessage : global::ProtoBuf.IExtensible
  {
    public ServersCreateSessionResultMessage() {}
    

    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private ulong _sessionid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sessionid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong sessionid
    {
      get { return _sessionid; }
      set { _sessionid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServersGetSessionsMessage")]
  public partial class ServersGetSessionsMessage : global::ProtoBuf.IExtensible
  {
    public ServersGetSessionsMessage() {}
    

    private string _tags = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tags", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tags
    {
      get { return _tags; }
      set { _tags = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServersGetSessionsResultMessage")]
  public partial class ServersGetSessionsResultMessage : global::ProtoBuf.IExtensible
  {
    public ServersGetSessionsResultMessage() {}
    
    private readonly global::System.Collections.Generic.List<SessionInfo> _servers = new global::System.Collections.Generic.List<SessionInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"servers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SessionInfo> servers
    {
      get { return _servers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServersUpdateSessionMessage")]
  public partial class ServersUpdateSessionMessage : global::ProtoBuf.IExtensible
  {
    public ServersUpdateSessionMessage() {}
    

    private ulong _sessionid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sessionid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong sessionid
    {
      get { return _sessionid; }
      set { _sessionid = value; }
    }

    private string _hostname = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hostname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hostname
    {
      get { return _hostname; }
      set { _hostname = value; }
    }

    private string _mapname = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mapname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mapname
    {
      get { return _mapname; }
      set { _mapname = value; }
    }

    private int _players = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int players
    {
      get { return _players; }
      set { _players = value; }
    }

    private int _maxplayers = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"maxplayers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxplayers
    {
      get { return _maxplayers; }
      set { _maxplayers = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServersUpdateSessionResultMessage")]
  public partial class ServersUpdateSessionResultMessage : global::ProtoBuf.IExtensible
  {
    public ServersUpdateSessionResultMessage() {}
    

    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServersDeleteSessionMessage")]
  public partial class ServersDeleteSessionMessage : global::ProtoBuf.IExtensible
  {
    public ServersDeleteSessionMessage() {}
    

    private ulong _sessionid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sessionid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong sessionid
    {
      get { return _sessionid; }
      set { _sessionid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServersDeleteSessionResultMessage")]
  public partial class ServersDeleteSessionResultMessage : global::ProtoBuf.IExtensible
  {
    public ServersDeleteSessionResultMessage() {}
    

    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}