//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: friends.proto
namespace NPx
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendsSetSteamIDMessage")]
  public partial class FriendsSetSteamIDMessage : global::ProtoBuf.IExtensible
  {
    public FriendsSetSteamIDMessage() {}
    
    private ulong _steamID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"steamID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong steamID
    {
      get { return _steamID; }
      set { _steamID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendsGetProfileDataMessage")]
  public partial class FriendsGetProfileDataMessage : global::ProtoBuf.IExtensible
  {
    public FriendsGetProfileDataMessage() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _npids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"npids", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<ulong> npids
    {
      get { return _npids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProfileDataResult")]
  public partial class ProfileDataResult : global::ProtoBuf.IExtensible
  {
    public ProfileDataResult() {}
    

    private ulong _npid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"npid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong npid
    {
      get { return _npid; }
      set { _npid = value; }
    }

    private byte[] _profile = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"profile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] profile
    {
      get { return _profile; }
      set { _profile = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendsGetProfileDataResultMessage")]
  public partial class FriendsGetProfileDataResultMessage : global::ProtoBuf.IExtensible
  {
    public FriendsGetProfileDataResultMessage() {}
    
    private readonly global::System.Collections.Generic.List<ProfileDataResult> _results = new global::System.Collections.Generic.List<ProfileDataResult>();
    [global::ProtoBuf.ProtoMember(1, Name=@"results", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProfileDataResult> results
    {
      get { return _results; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}